---
- include: user.yaml
- include: remove-sendmail.yaml
- include: dependencies.yaml
- include: python.yaml
- include: postgresql.yaml
- include: bundler.yaml
- include: mailman.yaml
- include: mailmanweb.yaml
- include: buildout.yaml
- include: mailman-post.yaml
- include: mailmanweb-post.yaml
- include: apache.yaml
